#!/bin/bash
#
# configuration application script.
# See the README for details.
#
# todo:
#  This doesn't work first-time on a new distro install yet, have had to manually set
#  some things and run it again. Fix this.
#
#--------------------------------------------------------------------------------
# Configuration settings
#--------------------------------------------------------------------------------
source settings
#--------------------------------------------------------------------------------

if [ ! "$PWD" = "$HOME/config" ]
then
    echo "config apply error: This script can only be run from the config_and_scripts repo root directory, cloned as \$HOME/config/."
    exit 0
fi

# xdg/freedesktop.org stuff
#--------------------------------------------------------------------------------
echo "Determining XDG variables..."
xdg_config_home="$(xdg-config-home)"
echo "xdg_config_home: $xdg_config_home"
xdg_cache_home="$(xdg-cache-home)"
echo "xdg_cache_home: $xdg_cache_home"
xdg_data_home="$(xdg-data-home)"
echo "xdg_data_home: $xdg_data_home"
xdg_state_home="$(xdg-state-home)"
echo "xdg_state_home: $xdg_state_home"
xdg_config_dirs="$(xdg-config-dirs)"
echo "xdg_config_dirs: $xdg_config_dirs"
xdg_data_dirs="$(xdg-data-dirs)"
echo "xdg_data_dirs: $xdg_data_dirs"

# Linux kernel stuff
#--------------------------------------------------------------------------------
LINUX_KERNEL_RELEASE="$(uname -r)"

# Link functions
#--------------------------------------------------------------------------------
create_link()
{
    ln -n -s "$1" "$2"
}
link_system_to_config()
{
    # Make sure the symlink put on the system has an absolute path to the file/dir in this config repo.
    target="$(realpath -s "$1")"
    link_name="$2"
    # NOTE: -e generally checks if a file exists, but if it is a symlink, this checks the followed symlink.
    if [ -e "$link_name" ] || [ -h "$link_name" ]
    then
        # The file already exists on the system.
        if [ -h "$link_name" ] && [[ $(readlink -f "$link_name")/ = $HOME/config/* ]]
        then
            # If the existing file is a symlink into this repo, overwrite without asking
            rm -r "$link_name"
            create_link "$target" "$link_name"
            echo "Updated link in system: $link_name ---> $target"
        else
            # Fail to create a symlink, as the user already has e.g. a ~/.vimrc on their system, which is not a symlink into this repo.
            echo "WARNING: $link_name already exists and isn't controlled by this config repo. Ignored."
        fi
    else
        create_link "$target" "$link_name"
        echo "Created link in system: $link_name ---> $target"
    fi
}
declare -a config_symlinks_to_gitignore
link_config_to_system()
{
    target="$1"
    link_name="$2"
    # TODO: Sanity-check that the link is to be placed in this repo.
    #       Or this might wipe a random file because of a typo...
    # NOTE: -e generally checks if a file exists, but if it is a symlink, this checks the followed symlink.
    if [ -e "$link_name" ] || [ -h "$link_name" ]
    then
        rm -r "$link_name"
    fi
    create_link "$target" "$link_name"
    echo "Created navigation link in config: $link_name ---> $target"
    config_symlinks_to_gitignore+=("$link_name")
}

# Setup symlinks on system to this config dir.
#--------------------------------------------------------------------------------
echo
link_system_to_config ./vim/runtime ~/.vim
link_system_to_config ./vim/vimrc.vim ~/.vimrc
link_system_to_config ./emacs/infokey ~/.infokey
link_system_to_config ./shell/profile.sh ~/.profile
link_system_to_config ./shell/bashrc.sh ~/.bashrc
link_system_to_config ./shell/bash_aliases.sh ~/.bash_aliases
link_system_to_config ./shell/bash_profile.sh ~/.bash_profile
link_system_to_config ./shell/bash_logout.sh ~/.bash_logout
link_system_to_config ./X/Xresources.txt ~/.Xresources
link_system_to_config ./X/xinitrc ~/.xinitrc
link_system_to_config ./X/xsession ~/.xsession
link_system_to_config ./screen/screenrc.txt ~/.screenrc
link_system_to_config ./screen/screendir ~/.screen
link_system_to_config ./readline/inputrc ~/.inputrc
link_system_to_config ./pager/lesskey.txt ~/.lesskey
link_system_to_config ./linux/pmaprc ~/.pmaprc

# git
mkdir -p "$xdg_config_home/git"
link_system_to_config ./git/gitconfig "$xdg_config_home/git/config"

# tig
# See `man tig`'s FILES section.
mkdir -p "$xdg_config_home/tig"
link_system_to_config ./git/tigrc "$xdg_config_home/tig/config"

# gdb
mkdir -p "$xdg_config_home/gdb"
link_system_to_config ./gdb/gdbinit.gdb "$xdg_config_home/gdb/gdbinit"

# mpv
mkdir -p "$xdg_config_home/mpv"
link_system_to_config ./mpv/mpv.conf "$xdg_config_home/mpv/mpv.conf"
link_system_to_config ./mpv/scripts "$xdg_config_home/mpv/scripts"

# mpd
mkdir -p "$xdg_config_home/mpd"
link_system_to_config ./mpd/mpd.conf "$xdg_config_home/mpd/mpd.conf"

# xmonad
mkdir -p ~/.xmonad
link_system_to_config ./xmonad/xmonad.hs ~/.xmonad/xmonad.hs

# elinks
mkdir -p ~/.elinks
link_system_to_config ./elinks/elinks.conf ~/.elinks/elinks.conf

# sxhkd
mkdir -p "$xdg_config_home/sxhkd"
link_system_to_config ./sxhkd/sxhkdrc "$xdg_config_home/sxhkd/sxhkdrc"

# lf
mkdir -p "$xdg_config_home/lf"
link_system_to_config ./lf/lfrc "$xdg_config_home/lf/lfrc"
link_system_to_config ./lf/icons "$xdg_config_home/lf/icons"

# mlterm
mkdir -p ~/.mlterm
link_system_to_config ./mlterm ~/.mlterm

# rofi
mkdir -p "$xdg_config_home/rofi"
link_system_to_config ./rofi/config.rasi "$xdg_config_home/rofi/config.rasi"


# kitty
mkdir -p "$xdg_config_home/kitty"
link_system_to_config ./kitty/kitty.conf "$xdg_config_home/kitty/kitty.conf"
link_system_to_config ./kitty/kittens "$xdg_config_home/kitty/kittens"

# ghostty
mkdir -p "$xdg_config_home/ghostty"
link_system_to_config ./ghostty/config.ghostty "$xdg_config_home/ghostty/config.ghostty"

# tmux
mkdir -p "$xdg_config_home/tmux"
link_system_to_config ./tmux/tmux.conf "$xdg_config_home/tmux/tmux.conf"

link_system_to_config ./i3 "$xdg_config_home/i3"
link_system_to_config ./zathura "$xdg_config_home/zathura"
link_system_to_config ./scripts ~/scripts
link_system_to_config source-highlight ~/.source-highlight
link_system_to_config qutebrowser "$xdg_config_home/qutebrowser"
link_system_to_config nvim/runtime "$xdg_config_home/nvim"
link_system_to_config debian/dpkg.cfg ~/.dpkg.cfg
link_system_to_config cool-retro-term/cool-retro-term-config "$xdg_config_home/cool-retro-term"
link_system_to_config freedesktop.org/user-dirs.conf "$xdg_config_home/user-dirs.conf"
link_system_to_config freedesktop.org/user-dirs.dirs "$xdg_config_home/user-dirs.dirs"
link_system_to_config freedesktop.org/user-dirs.locale "$xdg_config_home/user-dirs.locale"

# Setup symlinks in this directory to system files.
#--------------------------------------------------------------------------------
# This is for convenient navigation of config. The directory contents, and the symlinks themselves, are not tracked by git.
# The symlinks are not tracked because they could point to different places on different machines, e.g. with different usernames.
#
# These symlinks should be in .gitignore.
# TODO: How to do this automatically?

# system debian symlinks
echo
echo "Creating debian navigation symlinks in ./debian/..."
# apt
link_config_to_system /etc/apt/sources.list ./debian/@etc@apt@sources.list
link_config_to_system /etc/apt/sources.list.d ./debian/@etc@apt@sources.list.d
link_config_to_system /var/lib/apt ./debian/@var@lib@apt
link_config_to_system /var/log/apt ./debian/@var@log@apt
link_config_to_system /etc/apt ./debian/@etc@apt
link_config_to_system /etc/apt/apt.conf ./debian/@etc@apt@apt.conf
link_config_to_system /etc/apt/apt.conf.d ./debian/@etc@apt@apt.conf.d
# dpkg
link_config_to_system /var/lib/dpkg ./debian/@var@lib@dpkg
link_config_to_system /var/log/dpkg.log ./debian/@var@log@dpkg.log
link_config_to_system /etc/dpkg/dpkg.cfg ./debian/@etc@dpkg@dpkg.cfg
link_config_to_system /etc/dpkg/dpkg.cfg.d ./debian/@etc@dpkg@dpkg.cfg.d
link_config_to_system /var/lib/dpkg/available ./debian/@var@lib@dpkg@available
link_config_to_system /var/lib/dpkg/status ./debian/@var@lib@dpkg@status

# imagemagick
link_config_to_system /etc/ImageMagick-6 ./imagemagick/@etc@ImageMagick-6

# firefox
link_config_to_system /home/lucas/.mozilla/firefox ./firefox/firefox_user_directory

# system xdg symlinks
echo
echo "Creating debian xdg navigation symlinks in ./freedesktop.org/..."
link_config_to_system "$xdg_config_home" ./freedesktop.org/xdg_config_home
link_config_to_system "$xdg_cache_home" ./freedesktop.org/xdg_cache_home
link_config_to_system "$xdg_state_home" ./freedesktop.org/xdg_state_home
link_config_to_system "$xdg_data_home" ./freedesktop.org/xdg_data_home
link_config_to_system "$xdg_data_home/Trash" ./freedesktop.org/Trash
create_xdg_dir_symlinks()
{
    xdg_dirs_var="$1"
    is_data_dirs="$2"
    while read -r dirpath
    do
        if [ $opt_generate_dangling_system_symlinks -eq 1 ] || [ -d "$dirpath" ]
        then
            mangled_path="$(echo -n "$dirpath" | tr '/' '_' | tr ' ' '_')"
            link_config_to_system "$dirpath" "./freedesktop.org/$xdg_dirs_var@$mangled_path"
            # Collate xdg_data_dirs applications subdirectories under system_applications for convenience.
            link_config_to_system "$dirpath/applications" "./freedesktop.org/system_applications/$mangled_path"
        else
            echo "$xdg_dirs_var: $dirpath not found. Not creating symlink."
        fi
    done < <(echo "${!xdg_dirs_var}" | tr ':' '\n')
}
create_xdg_dir_symlinks xdg_config_dirs 0
create_xdg_dir_symlinks xdg_data_dirs 1

echo
echo "Creating general navigation symlinks..."
# Query the vim version.
# Note that it is expected that the system runs just one version of vim when invoked on the command line,
# although other vims may be installed, so VIMRUNTIME_NUMBER should be the same from any shell.
# This would not be the case with different vim versions installed and accessible by different PATHs e.g. in a login vs non-login shell.
#
# todo: This logic is not nice. Expects to be in /usr/local/share.
VIMRUNTIME_NUMBER="$(vim --version | head -1 | sed -En -e 's/^VIM - Vi IMproved ([[:digit:]]+\.[[:digit:]]+) .*$/\1/' -e 's/\.//p')"
link_config_to_system "/usr/local/share/vim/vim$VIMRUNTIME_NUMBER" ./vim/system_runtime

link_config_to_system /etc/inputrc ./readline/system_inputrc
link_config_to_system "$xdg_data_home/applications" ./freedesktop.org/user_applications
link_config_to_system "$xdg_config_home/mimeapps.list" ./freedesktop.org/mimeapps.list
link_config_to_system /usr/share/dbus-1 ./freedesktop.org/@usr@share@dbus-1
link_config_to_system /etc/dbus-1 ./freedesktop.org/@etc@dbus-1
link_config_to_system "$HOME/.python_history" ./python/python_history
link_config_to_system "$xdg_config_home/qutebrowser" ./qutebrowser/qutebrowser
link_config_to_system "$HOME/.bash_history" ./shell/bash_history
link_config_to_system "$xdg_state_home/nvim" nvim/state
link_config_to_system "/lib/modules/$LINUX_KERNEL_RELEASE" linux/modules
link_config_to_system "/etc/fstab" linux/@etc@fstab
link_config_to_system "/etc/mtab" linux/@etc@mtab
link_config_to_system "/etc/hosts" linux/@etc@hosts
link_config_to_system "/etc/resolv.conf" linux/@etc@resolv.conf
link_config_to_system "/etc/nsswitch.conf" linux/@etc@nsswitch.conf
# systemd
link_config_to_system "/etc/udev" "systemd/@etc@udev"
link_config_to_system "/etc/systemd" "systemd/@etc@systemd"
link_config_to_system "/etc/systemd/system.conf" "systemd/@etc@systemd@system.conf"
link_config_to_system "/etc/systemd/system.conf.d" "systemd/@etc@systemd@system.conf.d"
link_config_to_system "/etc/systemd/user.conf" "systemd/@etc@systemd@user.conf"
link_config_to_system "/etc/systemd/user.conf.d" "systemd/@etc@systemd@user.conf.d"
link_config_to_system "/lib/systemd" "systemd/@lib@systemd"
link_config_to_system "/lib/udev" "systemd/@lib@udev"
link_config_to_system "/usr/local/lib/udev" "systemd/@usr@local@lib@udev"
link_config_to_system "/run/udev" "systemd/@run@udev"
# grub
link_config_to_system "/boot/grub/grub.cfg" "grub/@boot@grub@grub.cfg"
link_config_to_system "/etc/grub.d" "grub/@etc@grub.d"
link_config_to_system "/etc/default/grub" "grub/@etc@default@grub"
link_config_to_system "/etc/default/grub.d" "grub/@etc@default@grub.d"

# Distribute "override" files to system directories.
#--------------------------------------------------------------------------------
echo
echo "Distributing "override" files to system directories."
# The system saves files in here, so don't want to copy those to this repo.
# Currently can't think of a nice symlink-overlay solution. Possible?
# overlayfs possibly, but way too much to do for such a simple thing. Also I think this supposes read-only for underlying directory.
# Or, can xdg be configured to look for applications in an additional user-specified directory?
(
    distribute_override_file()
    (
        override_file="$1"
        into_dir="$2"
        cp --target="$into_dir" "$override_file"
        echo "Inserted $override_file into $into_dir"
    )
    export -f distribute_override_file
    # Using find -exec to execute a bash function.
    # https://stackoverflow.com/questions/4321456/find-exec-a-shell-function-in-linux
    find freedesktop.org/xdg_override_applications/ -name '*.desktop' -exec bash -c 'distribute_override_file "$1" "$2"' -- {} "$xdg_data_home/applications" \;
    find freedesktop.org/xdg_override_autostart/ -name '*.desktop' -exec bash -c 'distribute_override_file "$1" "$2"' -- {} "$xdg_config_home/autostart" \;
)

# Configure application software.
# These are large-scale applications, e.g. DCC tools and game engines.
#--------------------------------------------------------------------------------
# Houdini
echo
houdini_version=20.5
houdini_dir="$HOME/houdini$houdini_version"
echo "Houdini directory: $houdini_dir"
if [ -d "$houdini_dir" ]
then
    # Houdini sometimes modifies the houdini user config directory, and want to
    # keep those files, so instead of linking the whole config dir, create
    # symlinks for each file/directory in it.
    fd . houdini/config --max-depth=1 | while read -r path
    do
        link_system_to_config "$path" "$houdini_dir/config/$(basename "$path")"
    done
fi
link_system_to_config ./houdini/houdini.env "$houdini_dir/houdini.env"
# links to system files
link_config_to_system "/opt/hfs$houdini_version/houdini/config" "./houdini/system_config"


# Configure XDG with e.g. an expected default web browser.
#--------------------------------------------------------------------------------
apply_xdg_settings()
{
    local desktop_file_dirs=("/usr/share/applications" "/usr/local/share/applications" "$HOME/.local/share/applications")

    desktop_file_exists()
    {
        local desktop_basename="$1"
        for dirpath in "${desktop_file_dirs[@]}"
        do
            if [ -f $dirpath/$desktop_basename.desktop ] ; then
                return 0
            fi
        done
        return 1
    }

    echo "Applying XDG settings..."
    local did_set_web_browser=0
    for app in "${opt_web_browser_priorities[@]}"
    do
        if desktop_file_exists "$app"
        then
            echo "$app.desktop found, setting it to the default web browser."
            xdg-settings set default-web-browser "$app.desktop"
            did_set_web_browser=1
            break
        fi
    done
    if [ $did_set_web_browser -eq 0 ] ; then
        echo "Couldn't find any of the web browser priorities: (${opt_web_browser_priorities[@]})"
        echo "Letting the system  use its own default web browser."
    fi
}
echo
apply_xdg_settings
unset -f apply_xdg_settings

# Generate a .gitignore file.
#--------------------------------------------------------------------------------
echo
echo "Creating .gitignore..."
cat base_gitignore > .gitignore
echo "Initialized with ./base_gitignore."
echo "" >> .gitignore
echo "# Ignore system symlinks" >> .gitignore
printf '%s\n' "${config_symlinks_to_gitignore[@]}" >> .gitignore
echo "Transient symlinks have been created in this repo. Added these lines to .gitignore:"
for line in "${config_symlinks_to_gitignore[@]}"
do
    # .gitignore doesn't parse leading ./, so remove this.
    fixed_line="$(echo "$line" | sed 's/^\.\///')"
    echo "$fixed_line" | tee -a .gitignore
done
