#!/bin/bash

pid="$1"
buf="$2"

[[ -v DIRSPACE_VIM_RUNTIME ]] || exit 1
[[ -d "$DIRSPACE_VIM_RUNTIME" ]] || exit 1

state_dir="$DIRSPACE_VIM_RUNTIME/state"
if [ ! -d "$state_dir" ]
then
    mkdir "$state_dir"
fi
buf_dir="$state_dir/$pid:$buf"
if [ -d "$buf_dir" ]
then 
    rm -r "$buf_dir"
fi
mkdir "$buf_dir"

while true
do
    foreground_pid="$(ps -o tpgid= "$pid" | tr -d ' ')"

    #TODO: Don't truncate it. See `man ps`.
    foreground_comm="$(ps -o comm "$foreground_pid" | tail -n +2 | head -1)"

    args="$(cat "/proc/$foreground_pid/cmdline" | tr '\0' '\n')"
    args_is_bash_script=0
    if [ "$(echo "$args" | head -1 | tr -d '\n')" = "$(which "$SHELL")" ]
    then
        script_path="$(echo "$args" | tail -n +2 | head -1 | tr -d '\n')"
        if [[ "$script_path" =~ ^/ ]] && [ -x "$script_path" ]
        then
            args_is_bash_script=1
        fi
    fi
    if [ $args_is_bash_script -eq 1 ]
    then
        foreground_args="$(echo "$args" | tail -n +3)"
    else
        foreground_args="$(echo "$args" | tail -n +2)"
    fi

    if [ -f "$buf_dir/foreground_pid" ]
    then
        old_foreground_pid="$(cat "$buf_dir/foreground_pid")"
        old_foreground_comm="$(cat "$buf_dir/foreground_comm")"
        old_foreground_args="$(cat "$buf_dir/foreground_args")"
        force_update=0
    else
        # Just set it to the new one, because they aren't set yet.
        old_foreground_pid="$foreground_pid"
        old_foreground_comm="$foreground_comm"
        old_foreground_args="$foreground_args"
        force_update=1
    fi
    echo "$foreground_pid" > "$buf_dir/foreground_pid"
    echo "$foreground_comm" > "$buf_dir/foreground_comm"
    echo "$foreground_args" > "$buf_dir/foreground_args"

    echo "pid: $foreground_pid"
    echo "comm: $foreground_comm"
    echo "args: $foreground_args"

    # Update the vim UI if necessary.
    if [ $force_update -eq 1 ] || [ ! "$old_foreground_comm" =  "$foreground_comm" ]
    then
        vim_remote_call RedrawTabPanel
    fi

    sleep 0.3
done
