#!/bin/bash
# albumlength:

min_sec ()
{
    local sec="$1"
    awk -v t="$sec" 'BEGIN {
        m = int(t / 60)
        s = t - m*60
        printf "%d %.6f\n", m, s
    }'
}

total=0
list=()
while read -r file
do
    mime="$(mimetype -b "$file")"
    if [[ "$mime" = audio/* ]]
    then
        t="$(ffprobe -v error -show_entries format=duration \
            -of default=noprint_wrappers=1:nokey=1 "$file")"
        if [ $? -ne 0 ]
        then
            >&2 echo "error: Could not calculate length of \"$file\""
        else
            list+=( "$(printf "%s\x1F%s" "$file" "$(min_sec "$t")")" )
            total="$(echo "$total + $t" | bc)"
        fi
    fi
done < <(fd -d1 -tf | sort -n)

printf '%s\n' "${list[@]}" | column -s $'\x1F' -t

min_sec "$total"
