#!/bin/bash
# blame: git blame wrapper

if ! ingit
then
    >&2 echo "blame failed: Not in a git repo"
    exit 1
fi

while read -r path line
do
    git --no-pager blame -L "$line,$line" -- "$path"
done < <(cat)
