#!/bin/bash
# blame: git blame wrapper

if ! ingit
then
    >&2 echo "blame failed: Not in a git repo"
    exit 1
fi

if [ $# -gt 0 ]
then
    (
        for f in "$@"
        do
            git --no-pager blame  -- "$f"
        done
    ) | less
else 
    while read -r path line
    do
        git --no-pager blame -L "$line,$line" -- "$path"
    done < <(cat)
fi
