#!/bin/bash
# desktop-next-wrap: go to the next virtual desktop, wrap around at last desktop

count="$(desktop-get-count)" || exit 1
focus="$(desktop-get-focus)" || exit 1

wmctrl -s "$(( ( focus + 1 ) % count ))"
