#!/bin/bash
# dirspace_fzf:

lines="$(cat ~/config/dirspace/dirspaces.txt | grep -v '^#' | grep -v '^\s*$')"

while read -r line
do
    path="$(echo "$line" | awk -F" -- " '{print $1}')"
    # Expand the leading ~ if there.
    path="${path/#\~/$HOME}"
    name="$(echo "$line" | awk -F" -- " '{print $2}')"
    if echo "$path" | grep -q "{}$" 2>/dev/null
    then
        expanding_path="${path::-2}"
        if [ ! -d "$expanding_path" ]
        then
            echo "skip: $expanding_path"
            # Skip silently.
            continue
        fi
        while read -r subpath
        do
            subdir="$(basename "$subpath")"
            expanding_name="${name//\{\}/$subdir}"
            expanding_name="${expanding_name//\{capitalize\}/${subdir^}}"
            expanding_name="${expanding_name//\{upper\}/${subdir^^}}"
            expanding_name="${expanding_name//\{lower\}/${subdir,,}}"
            echo "$expanding_name"
        done < <(fd . -td -d1 "$expanding_path")
    else
        echo "$path"
    fi
done < <(echo "$lines")
