#!/bin/bash
# dirspace_fifo_command:

session_id="$(dirspace_get_session)" || exit 1

FIFO=~/.local/share/dirspace/sessions/$session_id/fifo
if [[ ! -p "$FIFO" ]]
then
    >&2 echo "Dirspace session FIFO not found."
    exit 1
fi

quote_args ()
{
    echo "$(printf '%q ' "$@")"
}

fifo_command ()
{
    echo "$(quote_args "$@")" >> "$FIFO"
}

fifo_command "$@"
