#!/bin/bash
# dirspace_open:

if [[ ! -v DIRSPACE_RUNTIME ]]
then
    >&2 "Not in a dirspace session."
    exit 1
fi

dirspace="$(dirspace_get "$@")"
if [ $? -ne 0 ]
then
    >&2 echo "Couldn't find dirspace."
    exit 1
fi
dirspace_name="$(echo "$dirspace" | awk -F' -- ' '{print $1}')"
dirspace_path="$(echo "$dirspace" | awk -F' -- ' '{print $2}')"

# Check if it is open already.
for vim_runtime in $DIRSPACE_RUNTIME/vim/*
do
    vim_id="$(basename "$vim_runtime")"
    other_dirspace_name="$(cat "$vim_runtime/dirspace_name")"
    if [ "$dirspace_name" = "$other_dirspace_name" ]
    then
        # It is, switch to this screen window.
        screen -S "$DIRSPACE_SCREEN_ID" -X select "$vim_id" 
        exit 0
    fi
done

# It is not open, initialize it.

# Create the runtime directory for this window/vim.
DIRSPACE_VIM_RUNTIME="$(mktemp -d --tmpdir="$DIRSPACE_RUNTIME/vim" XXXX)"
vim_id="$(basename "$DIRSPACE_VIM_RUNTIME")"

# Create a globally unique vim servername.
# (Vim has its own runtime files for implementing vim server, so vim_id is not necessarily unique.
# It is only unique for this dirspace.)
VIM_SERVERNAME="$DIRSPACE_SESSION_ID.$vim_id"

screen -S "$DIRSPACE_SCREEN_ID" -X screen -t "$vim_id" ~/config/dirspace/dirspace_vim "$vim_id" "$dirspace_name" "$dirspace_path"
