#!/bin/bash
# dirspace_fzf:

lines="$(cat ~/config/dirspace/dirspaces.txt | grep -v '^#' | grep -v '^\s*$')"

paths=()
names=()
add ()
{
    paths+=("$1")
    names+=("$2")
}

while read -r line
do
    path="$(echo "$line" | awk -F" -- " '{print $1}')"
    name="$(echo "$line" | awk -F" -- " '{print $2}')"
    if echo "$path" | grep -q "/{}$" 2>/dev/null
    then
        expanding_path="${path::-2}"
        # Expand the leading ~ if there.
        expanding_path="${expanding_path/#\~/$HOME}"
        if [ ! -d "$expanding_path" ]
        then
            echo "skip: $expanding_path"
            # Skip silently.
            continue
        fi
        while read -r subpath
        do
            subdir="$(basename "$subpath")"
            expanding_name="${name//\{\}/$subdir}"
            expanding_name="${expanding_name//\{capitalize\}/${subdir^}}"
            expanding_name="${expanding_name//\{upper\}/${subdir^^}}"
            expanding_name="${expanding_name//\{lower\}/${subdir,,}}"
            add "${path::-2}$subdir" "$expanding_name"
        done < <(fd . -td -d1 "$expanding_path")
    else
        add "$path" "$name"
    fi
done < <(echo "$lines")

column -s $'\x1F' -t < <(
    for i in "${!paths[@]}"
    do
        printf "%s\x1F%s\n" "${names[$i]}" "${paths[$i]}"
    done
)
