#!/bin/bash
# dirspace_fzf_active:

selected="$( (
    while read -r dir
    do
        name="$(cat "$dir/dirspace_name")"
        path="$(cat "$dir/dirspace_path")"
        printf '%s\x1F--\x1F%s\n' "$name" "$path"
    done < <(fd -td -d1 . "$DIRSPACE_RUNTIME/vim")
) | column -t -s$'\x1F' | fzf )"

if [ $? -ne 0 ]
then
    exit
fi

path="$(echo "$selected" | awk -F' -- ' '{print $2}' | trs)"

dirspace_open "$path"
