#!/bin/bash
# dirspace_open:

dirspace="$(dirspace_get "$@")"
if [ $? -ne 0 ]
then
    >&2 echo "Couldn't find dirspace."
    exit 1
fi
dirspace_name="$(echo "$dirspace" | awk -F' -- ' '{print $1}')"
dirspace_path="$(echo "$dirspace" | awk -F' -- ' '{print $2}')"

echo "$dirspace_name"
