#!/bin/bash
# dirspace_edit:

session_id="$(dirspace_get_session)" || exit 1

FIFO=~/.local/share/dirspace/sessions/$session_id/fifo
if [[ ! -p "$FIFO" ]]
then
    >&2 echo "Dirspace session FIFO not found."
    exit 1
fi

quote_args ()
{
    echo "$(printf '%q ' "$@")"
}

fifo_command ()
{
    echo "$(quote_args "$@")" >> "$FIFO"
}

path="$1"
if [ ! -d "$path" ]
then
    exit 1
fi
resolved_path="$(
    cd "$path"
    pwd -L
)"
name="$(dirspace_get "$path")"
if [ $? -ne 0 ]
then
    name="$resolved_path"
fi
fifo_command open_dirspace "$name" "$resolved_path"
