#!/bin/bash
# dirspace_get:

if [ $# -ne 1 ]
then
    >&2 echo "give good args"
    exit 1
fi
arg_path="$1"
if [ ! -d "$arg_path" ]
then
    >&2 echo "Not a directory"
    exit 1
fi
input_path="$(realpath "$arg_path")"

lines="$(cat ~/config/dirspace/dirspaces.txt | grep -v '^#' | grep -v '^\s*$')"
num="$(echo "$lines" | wc -l)"

mapfile -t paths < <(echo "$lines" | awk -F" -- " '{print $1}')
mapfile -t names < <(echo "$lines" | awk -F" -- " '{print $2}')

name=""
for ((i=0 ; i<num; i++))
do
    path="${paths[i]}"
    # Expand the leading ~ if there.
    path="${path/#\~/$HOME}"

    if [ ! -d "$path" ]
    then
        # Skip silently.
        continue
    fi
    path="$(realpath "$path")"

    if [ "$input_path" = "$path" ]
    then
        name="${names[i]}"
        break
    fi
done

if [ ! -z "$name" ]
then
    # Dirspace found
    echo "$name"
    exit 0
else
    # Dirspace not found
    # Fail.
    exit 1
fi
