#!/bin/bash
# dpi: check if package is installed
#
# todo: Other install states?
if [ $# -eq 0 ]
then
    exit 0
fi
pass=installed
fail=no

while [ $# -gt 0 ]
do
    if dpkg -s "$1" >/dev/null 2>&1
    then
        printf '%s^%s\n' "$1" "$pass"
    else
        printf '%s^%s\n' "$1" "$fail"
    fi
    shift
done | column -t -s '^'
