#!/bin/sh
if [ "$#" -eq 0 ] ; then
    >&2 echo "Usage: dpkgs [commands...]"
    exit 0
fi
while [ "$#" -gt 0 ] ; do
    c16 blue ; echo "$(whereis "$1")" ; c16 --reset
    dpkg -S "$(realpath "$(which "$1")")"
    shift
done
