#!/bin/sh
#
# `dpkg -S` but takes a command argument which resolves to a path with `which`.

if [ "$#" -eq 0 ] ; then
    >&2 echo "Usage: dpkgs [commands...]"
    exit 0
fi
while [ "$#" -gt 0 ] ; do
    (
        c16 blue
        echo "$(whereis "$1")"
        c16 --reset
    ) >&2
    result="$(dpkg -S "$(realpath "$(which "$1")")")"
    echo "$result"
    if [ $? -eq 0 ]
    then
        echo "$result" | cutc 1 | x dpd | tail +2
    fi
    shift
done
