#!/bin/bash
# dtf:

if [ -z "$VIM_SERVERNAME" ]
then
    >&2 echo "Not in a vim server."
    exit 1
fi

cmd=("$@")
# Double the escapes for vim. --
command_string="$(printf '%q ' "${cmd[@]}" | sed 's/\\/\\\\/g')"

send_string='<C-\><C-n>:call DTFCommand("'"$command_string"'")<cr>'

vim --servername "$VIM_SERVERNAME" --remote-send "$send_string"

