#!/bin/bash
# emailkindle Email to kindle.
#
# Notes
#     Currently only through gmail relay using app password.
#     Currently only pdf and epub.
# Todo
#     - Should there be a delay between emails?
#         Google might limit it for spam.
#     - Automatic conversion?
#     - Use Calibre library?
#         Create a kindle format automatically and send from there.

if [ $# -eq 0 ]
then
    >&2 echo "give good args"
    exit 1
fi

for arg in "$@"
do
    if [ ! -f "$arg" ]
    then
        >&2 echo "error: $arg is not a file."
        exit 1
    fi
    mime="$(mimetype -b "$arg")"
    if     ! [ "$mime" = "application/epub+zip" ] \
        && ! [ "$mime" = "application/pdf" ]
    then
        >&2 echo "error: $arg is not a valid filetype."
        exit 1
    fi
done

kindle_config_dir=~/.config/config_hidden/kindle

if [ ! -f "$kindle_config_dir/from_address" ]
then
    >&2 echo "error: Need to store relay address in $kindle_config_dir/from_address"
    exit 1
fi
ADDRESS="$(cat "$kindle_config_dir/from_address")"

if [ ! -f "$kindle_config_dir/kindle_address" ]
then
    >&2 echo "error: Need to store kindle address in $kindle_config_dir/kindle_address"
    exit 1
fi
KINDLE_ADDRESS="$(cat "$kindle_config_dir/kindle_address")"

echo "from: $ADDRESS"
echo "to: $KINDLE_ADDRESS"

if [ -f "$kindle_config_dir/google_app_password" ]
then
    echo "Reading google app password from $kindle_config_dir/google_app_password"
    PASS="$(cat "$kindle_config_dir/google_app_password")"
else
    echo "Entering app password manually"
    echo "(To skip this, save the app password at $kindle_config_dir/google_app_password)"
    read -s -p "app password: " PASS
    echo
fi

if [ "${#PASS}" -ne 16 ]
then
    >&2 echo "error: app password must be 16 characters"
    exit 1
fi

echo "Sending books..."
# PORT=465
PORT=587
for file in "$@"
do
    calibre-smtp --relay smtp.gmail.com \
                 --port "$PORT" \
                 --encryption-method TLS \
                 --username "$ADDRESS" \
                 --password "$PASS" \
                 --attachment "$file" \
                 --subject "book" \
                 "$ADDRESS" \
                 "$KINDLE_ADDRESS" \
                 "book"
    if [ $? -eq 0 ]
    then
        echo "Success: $file"
    else
        echo "Error: $file"
    fi
done

