#!/bin/bash
# fetch-ebook-isbn: get isbn from fetch-ebook-metadata
# Note: Don't use --opf, expects stdout from fetch-ebook-metadata.

set -e
metadata="$(fetch-ebook-metadata "$@")"
echo "$metadata" | grep -E "^Identifier" | sed -n 's/.*\(isbn:[0-9]\+\).*/\1/p' | cutc 2
