#!/bin/bash
#
# List the default gcc system includes for a file.

opt_c=0
opt_cxx=0
language_specified=0
while [[ $# -gt 0 ]]; do
    # Case insensitive.
    opt="${1,,}"
    case $opt in
    c++|cpp|cxx)
        opt_cxx=1
        language_specified=1
        shift
        ;;
    c)
        opt_c=1
        language_specified=1
        shift
        ;;
    esac
done

function display_includes
{
    local lang=$1
    echo | gcc -x"$lang" -E -v - 2>&1 \
         | sed -ne '/> search starts here/,/End of search list./ p' \
         | tail +2 \
         | head -n -1 \
         | sed 's/^ *//;s/ *$//'
}

if [[ $opt_c -eq 1 ]] ; then
    display_includes c
fi

if [[ $opt_cxx -eq 1 ]] ; then
    display_includes c++
fi

if [[ $language_specified -eq 0 ]] ; then
    c16 blue ; echo C ; c16 --reset
    display_includes c
    c16 blue ; echo C++ ; c16 --reset
    display_includes c++
fi

