#!/bin/bash
#
# Copy argument files to kindle.
# Options:
#    -e     eject afterwards
user=lucas

DIR="/media/$user/Kindle"
DOCUMENTS="/media/$user/Kindle/documents"

do_eject=0

if [ ! -d "$DIR" ]
then
    >&2 echo "Kindle is not mounted"
    exit 1
fi

while [[ "$#" -gt 0 ]]
do
    filename="$1"
    if [ "$filename" = "-e" ]
    then
        do_eject=1
    elif [[ ! -f "$filename" ]]
    then
        >&2 echo "File \"$filename\" not found."
    else
        cp "$filename" "$DOCUMENTS"
        echo "Copied \"$filename\" to kindle."
    fi
    shift
done

if [[ $do_eject -eq 1 ]]
then
    if ! eject "$DIR"
    then
        2>&1 echo "Failed to eject kindle. Make sure to eject with correct privileges before unplugging."
    fi
fi
