#!/bin/bash
# ldsonames: list SONAMEs from ldpaths output
# Notes:
#     This can have duplicates.
#     This may be better computed directly from ldconfig -p.

ldpaths | xi sh -c "readelf -d {} | grep SONAME" | while read -r line
do
    if [[ $line =~ \[(.*)\]$ ]]
    then
        echo "${BASH_REMATCH[1]}"
    fi
done
