#!/bin/bash
# linkbook:

name="$1"
search="$2"

calibre_link="$(mktemp --tmpdir="$HOME/drive/books/links" XXXX)"

echo "$search" >> "${calibre_link}.search"

ln -s "$calibre_link" "$name"

calibre-calculate-links
