#!/bin/bash
# mansec: alias and helper for `man -s 2 -k .`
usage ()
{
    >&2 echo "Usage: mansec <section number 1-9> [optional search]"
}

if [ $# -eq 0 ]
then
    usage
    exit 1
fi
section_number="$1"
shift
# validate this is a manpage section number
re='^[1-9]$'
if ! [[ $section_number =~ $re ]]
then
    >&2 echo "error: Unknown section number \"$section_number\"."
    usage
    exit 1
fi

if [ $# -eq 1 ]
then
    exec man -s "$section_number" -k . | grep -i "$@"
else
    exec man -s "$section_number" -k .
fi
