#!/bin/bash
# mansc: alias and helper for `man -s 2 -k .`, for searching system calls
if [ $# -gt 1 ]
then
    >&2 echo "Usage: mansc [optional search]"
    exit 1
fi
if [ $# -eq 1 ]
then
    exec man -s 2 -k . | grep -i "$@"
else
    exec man -s 2 -k .
fi
