#!/bin/bash
# mimg: "mimetype grep", filter by mimetype
if [ $# -ne 1 ]
then
    >&2 echo "Usage: mimg <pattern>  //stdin: lines to filter"
    exit 1
fi
pattern="$1"
while read -r line
do
    mimetype "$line"| grep -E " *[^ ]*$pattern[^ ]*$" | rev | cut -d: -f 2- | rev
done
