#!/bin/bash
# mpvalt: launch mpv in fullscreen on all virtual desktops on secondary monitor, and free from the window manager.
# Used for playing background noise, like a scenic video, when not using the other monitor.

pid="$(d mpv --script=~/config/mpv/scripts_storage/mpris.so --loop "$@")"
wid="$(waitwindow "$pid")"

# Find monitor offset.
# wmctrl uses X's single all-monitor screen coordinates which Xrandr maps monitor geometry to.
monitor_geometry="$(xrandr | grep " connected " | grep ^DP-0 | cut -d' ' -f 3)"
if [[ ! $monitor_geometry =~ ^([0-9]+)x([0-9]+)\+([0-9]+)\+([0-9]+)$ ]]
then
    echo "monitor_geometry failed"
    exit 1
fi
WIDTH=${BASH_REMATCH[1]}
HEIGHT=${BASH_REMATCH[2]}
X=${BASH_REMATCH[3]}
Y=${BASH_REMATCH[4]}
wmctrl -i -r "$wid" -e 0,$X,$Y,$WIDTH,$HEIGHT
wmctrl -i -r "$wid" -b add,fullscreen
wmctrl -i -r "$wid" -b add,sticky
sleep 1
xwifree "$wid"
