#!/bin/bash
# opacity-firefox: change opacity of firefox windows
# Doesn't apply to new firefox windows, will have to run this again.

if [ $# -eq 0 ]
then
    opacity=80
elif [ $# -eq 1 ]
then
    opacity="$1"
    if [[ ! "$opacity" =~ ^[0-9]+$ ]] || [ $opacity -lt 0 ] || [ $opacity -gt 100 ]
    then
        >&2 echo "Invalid number, give number 0-100."
        exit 1
    fi
else
    >&2 echo "give good args"
    exit 1
fi

windows="$(wmctrl -l | grep ' Mozilla Firefox$' | getcol 1 | tr '\n' ' ')"
if [ -z "$windows" ]
then
    >&2 echo "No firefox windows found."
    exit 0
fi

# Convert the percentage to 32-bit range.
opacity_32=$((opacity * 42949673))
if [ $opacity_32 -gt 4294967295 ]
then
    opacity_32=4294967295
fi
# Convert to hex code.
opacity_hex=$(printf '0x%x' $opacity_32)

# Set the opacity on the windows.
for win in $windows
do
    xprop -id $win -f _NET_WM_WINDOW_OPACITY 32c -set _NET_WM_WINDOW_OPACITY $opacity_hex
done
