#!/bin/bash
# playalbum: play album in this directory
# Or, given a song file in that directory, cd to it first.
#
# Assumes the song names are prefixed with the number position in the album.

if [ $# -eq 1 ]
then
    if [ -f "$1" ]
    then
        dir="$(dirname "$1")"
    elif [ -d "$1" ]
    then
        dir="$1"
    else
        >&2 echo "error: $f is not a file or directory."
        exit 1
    fi
    cd "$dir"
    shift
fi

songs=()
while read -r file
do
    mime="$(mimetype -b "$file")"
    if [[ "$mime" = audio/* ]]
    then
        songs+=("$file")
    fi
done < <(fd -d1 -tf | sort -n)

mpv --no-video "${songs[@]}"

