#!/bin/bash

pids=()
while [[ $# -gt 0 ]] ; do
    pids+=("$1")
    shift
done

ppid()
{
    pid="$1"
    stat_file="/proc/$pid/stat"
    if [[ ! -f "$stat_file" ]] ; then
        return 1
    fi
    cat "$stat_file" | tr ' ' '\n' | tail -49 | head -1
    return 0
}

ppids=()
for pid in "${pids[@]}" ; do
    ppids+=("$(ppid "$pid")")
    if [[ $? -ne 0 ]] ; then
        >&2 printf 'bad pid: %s\n' "$pid"
        exit 1
    fi
done

if [[ "${#ppids[@]}" -ne 0 ]] ; then
    echo "${ppids[@]}"
fi
