#!/bin/bash

# ppids p ...
# Show ps output of ppids. 
ps_mode=0
if [ $# -gt 0 ] && [ "$1" = "p" ]
then
    ps_mode=1
    shift
fi

ppid_ignore_next=0
if [[ $# -eq 0 ]]
then
    pid=$$
    # The pid of this script's shell is transient and the caller won't care about it, so ignore it.
    ppid_ignore_next=1
else
    pid="$1"
fi

ppids=()
cur_pid="$pid"
while [[ "$cur_pid" -ne 0 ]]
do
    if [[ $ppid_ignore_next -eq 1 ]]
    then
        ppid_ignore_next=0
    else
        ppids+=("$cur_pid")
    fi
    cur_pid="$(ppid "$cur_pid")"
    if [[ $? -ne 0 ]]
    then
        exit 1
    fi
done

if [ $ps_mode -eq 1 ]
then
    echo "${ppids[@]}" | x ps
else
    echo "${ppids[@]}"
fi
