#!/bin/bash
#
# Show dpkg dependencies and descriptions.

usage () {
    echo "Usage:"
    echo "    rdepends PACKAGE"
}

if [[ "$#" -ne 1 ]] ; then
    usage
    exit 1
fi

pkg_name="$1"

apt-rdepends "$pkg_name" 2>/dev/null |
sed -E -n -e 's/^  Depends: ([^ ]+).*$/echo "  \1" ; dpkgdesc \1/ep' \
          -e 's/^([^ ].*)/c16 blue ; echo \1 ; dpkgdesc \1 ; c16 --reset/ep'
