#!/bin/bash
# readme: Utility for readme files and other software information.
# -d <package_name>: Output README for a package.
# -D <package_name>: Output README.Debian for a package.
# -p No pager
# -m <package_name>: Output man pages for a package.
# -i <package_name>: Information about what is available for this package.
# -u <package_name>: Package project URLs (version control, homepage, debian/copyright Source entry)
# -U <package_name>: Package project homepage URL

usage ()
{
    local exit_code="$1"
    2>&1 echo "Try 'readme --help' or 'readme -h' for more information."
    exit "$exit_code"
}

func=
func_args=()
set_func ()
{
    local func_name="$1"
    shift
    if [ -n "$func" ]
    then
        usage 1
    fi
    func="$func_name"
    while [ "$#" -gt 0 ]
    do
        func_args+=("$1")
        shift
    done
}

if [ -t 1 ]
then
    if [ ! -z "${PAGER+x}" ]
    then
        #todo: Check, can PAGER contain arguments?
        pager_command="$PAGER"
    else
        pager_command=less
    fi
else
    pager_command=cat
fi

while getopts ":hpd:i:D:m:u:U:-:" opt
do
    case $opt in
        h)
            set_func help
            ;;
        d)
            set_func dpkg_readme "$OPTARG"
            ;;
        D)
            set_func dpkg_readme_debian "$OPTARG"
            ;;
        p)
            pager_command=cat
            ;;
        m)
            set_func dpkg_manpages "$OPTARG"
            ;;
        i)
            set_func dpkg_information "$OPTARG"
            ;;
        u)
            set_func dpkg_urls "$OPTARG"
            ;;
        U)
            set_func dpkg_homepage_url "$OPTARG"
            ;;
        *)
            case $OPTARG in
                d)
                    [ -n "$func" ] && usage 1 || 2>&1 echo "Usage: -d <package name> "
                    ;;
                D)
                    [ -n "$func" ] && usage 1 || 2>&1 echo "Usage: -D <package name> "
                    ;;
                *)
                    [ -n "$func" ] && usage 1 || 2>&1 echo "Unknown flag -$OPTARG"
                    ;;
            esac
            exit 1
            ;;
    esac
done

[ $OPTIND -eq 1 ] && usage 0

func_help ()
{
    echo "readme:"
    echo "    -d <package_name>: Print debian README file from /usr/share/doc/<package_name>."
    echo "    -D <package_name>: Print debian README.Debian file from /usr/share/doc/<package_name>."
}

do_check_dpkg_installed ()
{
    local package_name="$1"
    if ! dpkg -l "$package_name" >/dev/null 2>&1
    then
        2>&1 echo "error: Package \"$package_name\" is not found."
        return 1
    fi
    if ! dpkg -l "$package_name" 2>/dev/null | tail -1 | grep -q -E '^ii '
    then
        2>&1 echo "error: Package \"$package_name\" is uninstalled."
        return 1
    fi
}

get_dpkg_readme_files ()
{
    local package_name="$1"
    shift
    local extensions=()
    while [ "$#" -gt 0 ]
    do
        extensions+=("$1")
        shift
    done

    do_check_dpkg_installed "$package_name" || return 1

    local package_dir="/usr/share/doc/$package_name"

    for extension in "${extensions[@]}"
    do
        if [ -f "$package_dir/README$extension" ]
        then
            echo "$package_dir/README$extension"
        elif [ -f "$package_dir/README$extension.gz" ]
        then
            echo "$package_dir/README$extension.gz"
        else
            echo "<none>"
        fi
    done
}

dpkg_readme_common ()
{
    local extensions_mode="$1"
    local extensions=()
    [ "$extensions_mode" = "normal" ] && extensions=("" ".md" ".txt" ".rst") || extensions=(".Debian")
    local package_name="$2"

    local package_dir="/usr/share/doc/$package_name"
    if [ ! -d "$package_dir" ]
    then
        2>&1 echo "error: Non-existant $package_dir."
        return 1
    fi

    local files="$(get_dpkg_readme_files "$package_name" "${extensions[@]}")"
    local i=0
    while read -r f
    do
        local extension="${extensions[$i]}"
        if [ "$f" != "<none>" ]
        then
            case $(mimetype -b "$f") in
                application/gzip)
                    gunzip -c "$f" | "$pager_command"
                    return 0
                    ;;
                *)
                    cat "$f" | "$pager_command"
                    return 0
                    ;;
            esac
        fi
        ((i++))
    done < <(echo "$files")
    # no readme was found
    for extension in "${extensions[@]}"
    do
        2>&1 echo "error: README$extension file not found in $package_dir"
    done

    return 1
}

func_dpkg_readme ()
{
    dpkg_readme_common normal "$@"
}

func_dpkg_readme_debian ()
{
    dpkg_readme_common debian "$@"
}

func_dpkg_manpages ()
{
    local package_name="$1"

    do_check_dpkg_installed "$package_name" || return 1
    mapfile -t dpkg_manpages_files < <(dpkg -L "$package_name" \
                                        | grep -E '^/usr/share/man/man[[:digit:]]/' \
                                        | xargs -r basename -a \
                                        | sort \
                                        | uniq)

    #note: Not using pager for this output as intended to be copied.
    (
        for i in {1..9}
        do
            local section_manpages=()
            for f in ${dpkg_manpages_files[@]}
            do
                if echo "$f" | grep -q -E '\.'$i'\.gz$'
                then
                    section_manpages+=("$(basename -s .$i.gz "$f")")
                fi
            done
            for var in ${section_manpages[@]}
            do
                echo "$var" | sed "s/^/man $i /"
            done
        done
    )
}

sharedlib_info ()
{
    library_path="$1"
    echo "dynamic links:"
    ldd "$library_path" | sed 's/^\t//' | cutw 1 | indent 1
}

manpage_section_descriptions=(
"<zero section doesn't exist>"
"Executable programs or shell commands"
"System calls (functions provided by the kernel)"
"Library calls (functions within program libraries)"
"Special files (usually found in /dev)"
"File formats and conventions, e.g. /etc/passwd"
"Games"
"Miscellaneous (including macro packages and conventions), e.g. man(7), groff(7)"
"System administration commands (usually only for root)"
"Kernel routines [Non standard]"
)

func_dpkg_information ()
{
    local package_name="$1"
    if ! dpkg -l "$package_name" >/dev/null 2>&1
    then
        2>&1 echo "error: Package \"$package_name\" not found."
        return 1
    fi
    echo "name: $package_name"
    #todo: Multiple architectures, which one?
    dpkg-query --show -f='status: ${Status} (${db:Status-Abbrev})\n' "$package_name" | head -1

    # If not installed abort now, following information requires an installed package.
    do_check_dpkg_installed "$package_name" || return 1

    local package_dir="/usr/share/doc/$package_name"

    local manpages="$(func_dpkg_manpages "$package_name" 2>/dev/null)"
    if [ ! -z "$manpages" ]
    then
        for i in {1..9}
        do
            local section_manpages="$(echo -n "$manpages" | grep -E "^man $i " | cutw 3)"
            if [ ! -z "$section_manpages" ]
            then
                echo "man$i: ${manpage_section_descriptions[$i]}"
                echo "$section_manpages" | while read -r page ; do
                    whatis "$page" | grep -E "^$page \($i\) " | indent 1
                done
            fi
        done
    fi
    echo "Description:"
    dpkgdesc "$package_name" | tail +2
    echo "README:"
    get_dpkg_readme_files "$package_name" '' '.md' | grep -v -E '^<none>$' | indent 1
    echo "README.Debian:"
    get_dpkg_readme_files "$package_name" '.Debian' | grep -v -E '^<none>$' | indent 1
    # Changelogs.
    # Assuming each of these is installed at /usr/share/doc not under any subdirectory.
    echo "changelogs:"
    if [ -d "$package_dir" ]
    then
        fd -d 1 changelog "$package_dir" | indent 1
    fi

    # Show executable information.
    echo "executables:"
    dpkg -L "$package_name" | xargs ls -d -l | grep ^-rwx | rcutw 1 | while read -r f ; do
        local mime="$(mimetype -b "$f")"
        printf '    %s: %s\n' "$f" "$mime"
        if [ "$mime" = "application/x-sharedlib" ]
        then
            sharedlib_info "$f" | indent 2
        fi
    done
    # Show shared-library information.
    # Assume non-executable, and with a .so... suffix.
    echo "shared libraries:"
    local shared_library_files="$(dpkg -L "$package_name" | xargs ls -d -l | grep -E '^-[-r][-w]-' | rcutw 1 | grep -E '\.so(\.[[:digit:]]+)?(\.[[:digit:]]+)?(\.[[:digit:]]+)?')"
    while read -r f
    do 
        local mime="$(mimetype -b "$f")"
        printf '    %s: %s\n' "$f" "$mime"
        if [ "$mime" = "application/x-sharedlib" ]
        then
            sharedlib_info "$f" | indent 2
        fi
    done < <(echo "$shared_library_files")


    # Show xdg desktop files.
    #todo: This is VERY slow.
    echo "xdg desktop files:"
    while read -r line
    do
        local f="$(echo "$line" | cutc 1)"
        local mime="$(echo "$line" | rcutw 1)"
        if [ "$mime" = "application/x-desktop" ]
        then
            echo "    $f"
            cat "$f" | grep -m 1 -E '^[[:space:]]*Exec=' | sed 's/^[[:space:]]*//' | indent 2
        fi
    done < <(dpkg -L "$package_name" | xargs mimetype)

    # pkg-config
    # (Assume .pc files are for pkg-config.)
    echo "pkg-config:"
    dpkg -L "$package_name" | grep -E '\.pc$' | indent 1

    #idea: systemd
}

func_dpkg_urls ()
{
    local package_name="$1"
    if ! dpkg -l "$package_name" >/dev/null 2>&1
    then
        2>&1 echo "error: Package \"$package_name\" not found."
        return 1
    fi

    # Homepage URL
    dpkg -s "$package_name" | grep "^Homepage: " | cutw 2

    # Copyright Source URL
    local copyright_file="/usr/share/doc/$package_name/copyright"
    if [ -f "$copyright_file" ]
    then
        cat "$copyright_file" | grep "^Source: " | cutw 2
    fi

    # Version control URLs
    #https://www.debian.org/doc/debian-policy/ch-controlfields.html#version-control-system-vcs-fields
}

func_$func "${func_args[@]}"
