#!/bin/bash
# readme: Utility for readme files.
# -d <package_name>: Output README for a dpkg package.
# -D <package_name>: Output README.Debian for a dpkg package.

usage ()
{
    local exit_code="$1"
    2>&1 echo "Try 'readme --help' or 'readme -h' for more information."
    exit "$exit_code"
}

func=
func_args=()
set_func ()
{
    local func_name="$1"
    shift
    if [ -n "$func" ]
    then
        usage 1
    fi
    func="$func_name"
    while [ "$#" -gt 0 ]
    do
        func_args+=("$1")
        shift
    done
}
while getopts ":hd:D:-:" opt
do
    case $opt in
        #-)
        #    case "$OPTARG" in
        #        help)
        #            ;;
        #        *)
        #            ;;
        #    esac
        #    ;;
        h)
            set_func help
            ;;
        d)
            set_func dpkg_readme "$OPTARG"
            ;;
        D)
            set_func dpkg_readme_debian "$OPTARG"
            ;;
        *)
            case $OPTARG in
                d)
                    [ -n "$func" ] && usage 1 || 2>&1 echo "Usage: -d <package name> "
                    ;;
                D)
                    [ -n "$func" ] && usage 1 || 2>&1 echo "Usage: -D <package name> "
                    ;;
                *)
                    [ -n "$func" ] && usage 1 || 2>&1 echo "Unknown flag -$OPTARG"
                    ;;
            esac
            exit 1
            ;;
    esac
done

[ $OPTIND -eq 1 ] && usage 0

func_help ()
{
    echo "readme:"
    echo "    -d <package_name>: Print debian README file from /usr/share/doc/<package_name>."
    echo "    -D <package_name>: Print debian README.Debian file from /usr/share/doc/<package_name>."
}

func_dpkg_readme ()
{
    local package_name="$1"

    if ! dpkg -l "$package_name" >/dev/null 2>&1
    then
        2>&1 echo "error: Package \"$package_name\" is not installed."
        exit 1
    fi

    local package_dir="/usr/share/doc/$package_name"
    if [ ! -d "$package_dir" ]
    then
        2>&1 echo "error: Non-existant $package_dir."
        exit 1
    fi

    if [ -f "$package_dir/README" ]
    then
        cat "$package_dir/README"
    elif [ -f "$package_dir/README.gz" ]
    then
        gunzip -c "$package_dir/README.gz"
    else
        2>&1 echo "error: README file not found in $package_dir"
        exit 1
    fi
}

func_dpkg_readme_debian ()
{
    return
}

func_$func "${func_args[@]}"
