#!/bin/bash
# sds: alias and helper for systemctl, mnemonic "systemd systemctl"

check_usage ()
{
    local num_args="$1"
    local usage_message="$2"
    local actual_num_args="$(($#-2))"
    if [ $num_args -ne $actual_num_args ]
    then
        >&2 echo "Usage: $usage_message"
        exit 1
    fi
}

# Implements own user flag for convenience.
user=system
if [ $# -ge 1 ] && [ "$1" = "--user" ]
then
    user=user
    shift
fi

# Call systemctl with the correct --system or --user.
# Below, call this instead of systemctl, otherwise the sds flag won't be respected.
systemctl_command="systemctl --$user"

# Shortcuts
if [ $# -ge 1 ]
then
    case "$1" in
        # ls: mnemonic for "list"
        lsu)
            set -- "list-units" "${@:2}"
            ;;
        lss)
            set -- "list-sockets" "${@:2}"
            ;;
        lst)
            set -- "list-timers" "${@:2}"
            ;;
        lsd)
            set -- "list-dependencies" "${@:2}"
            ;;
        lsuf)
            set -- "list-unit-files" "${@:2}"
            ;;
        lsufp)
            # List unit file paths.
            # systemctl is referencing @.service file with @service.
            # Skipping unfound unit files. Not sure why some aren't found, should this be the case?
            # e.g. blockdev@.target, `show blockdev@target` works but not status.
            $systemctl_command list-unit-files \
                | head -n -2 \
                | tail +2 \
                | cutw 1 \
                | sed 's/@\./@/g' \
                | xargs -i $systemctl_command show -p FragmentPath -- {} \
                | cut -d= -f 2- \
                | grep -v -E '^$'
            exit 0
            ;;
        # q: Mnemonic for "query"
        qf)
            set -- "is-failed" "${@:2}"
            ;;
        qe)
            set -- "is-enabled" "${@:2}"
            ;;
        qa)
            set -- "is-active" "${@:2}"
            ;;
        qsr)
            set -- "is-system-running" "${@:2}"
            ;;
        # Other
        s)
            set -- "status" "${@:2}"
            ;;
        h)
            set -- "show" "${@:2}"
            ;;
        c)
            set -- "cat" "${@:2}"
            ;;
        p|sp|pc|spc)
            # Show path of unit file
            # Note: -P in newer versions removes prefix.
            check_usage 2 "sds p <unit>" "$@"
            if [[ "$1" =~ ^s.*$ ]]
            then
                # Optionally show status as well
                $systemctl_command status "$2"
            fi
            path="$(systemctl_command show -p FragmentPath -- "$2" | cut -d= -f 2-)"
            echo "$path"
            if [[ "$1" =~ ^.*c$ ]]
            then
                # Optionally cat path as well
                cat "$path"
            fi
            exit 0
            ;;
    esac
fi

$systemctl_command "$@"
