#!/bin/bash
# stracev: Pipe strace with both program stdout and strace stderr to vim.

output="$(strace 2>&1 "$@")"
ret=$?
if [ $ret -eq 0 ]
then
    echo "$output" | v
    exit 0
fi
# strace failed, assume all output is it's stderr for its own failure.
>&2 echo "$output"
exit $ret
