#!/bin/bash

# tmux new-session \; \
#     split-window -v \; \
#     attach \; \
#     resize-pane -y 10 \; \
#     rename-window editing \; \
#     new-window \; \
#     rename-window build \; \
#     new-window \; \
#     rename-window logs \; \
#     select-window -t 0 \; \
#     select-pane -t 0

screen
