#!/bin/bash
#
#--------------------------------------------------------------------------------
# termdesk
#--------------------------------------------------------------------------------

tempfile="$(tempfile 2>/dev/null)"
export TERMDESK_ID="$tempfile"
pwd > $TERMDESK_ID
vimnewenv screen -S termdesk vim --servername "$TERMDESK_ID" -c "call VimTermDeskInit()"
