#!/bin/bash
# vidbg: cycle video backgrounds

vids="$(fd -tf -d1 . ~/drive/videos/vidbg)"
num_vids="$(echo "$vids" | wc -l)"
if [ ! -f /tmp/vidbgnumber ]
then
    echo 0 > /tmp/vidbgnumber
else
    n="$(cat /tmp/vidbgnumber)"
    n="$(( ( n + 1 ) % num_vids ))"
    echo "$n" > /tmp/vidbgnumber
fi

vid="$(echo "$vids" | sel $((n+1)))"

#todo: Don't kill all mpvs
pkill '^mpv$'

pid="$(d mpvbg --no-audio --video-zoom=0.15 "$vid")"
