#!/bin/bash
# vim_remote_expr: alias for --remote-expr automatically using VIM_SERVERNAME.

if [[ ! -v VIM_SERVERNAME ]]
then
    exit 1
fi

exec vim --servername "$VIM_SERVERNAME" --remote-expr "$@"
