#!/bin/bash
#
# TODO:
# Argument passing.
# Input checking.

if ! command -v jq &>/dev/null
then
    >&2 echo "jq must be installed"
    exit 1
fi

if [ -z "$VIM_SERVERNAME" ]
then
    >&2 echo "Not in a vim server"
    exit 1
fi

if [ $# -eq 0 ]
then
    >&2 echo "A vim function name must be given."
    exit 1
fi

vim_function_name="$1"
shift
# Make sure vim function name is in the correct form.
# This is a string starting with a letter, which can contain numbers and dots
# (for dictionary access to funcrefs, see :help function).
#todo: following . must be identifiers too, e.g. no foo.3
vim_function_regex='^[A-Za-z][A-Za-z0-9\.]*$'
if [[ ! "$vim_function_name" =~ $vim_function_regex ]]
then
    >&2 echo "Ill-formed vim function name given: $vim_function_name"
    exit 1
fi
    
vim_function_extra_args=()
while [[ $# -gt 0 ]]
do
    vim_function_extra_args+=("$1")
    shift
done

json_contents="$(cat)"
if ! echo "$json_contents" | jq . &>/dev/null
then
    >&2 echo "Invalid json"
    exit 1
fi

json_temp_file="$(mktemp)"
echo "$json_contents" > "$json_temp_file"

send_string='<C-\><C-n>:call VimJSONRPC("'"$vim_function_name"'", "'"$json_temp_file"'")<cr>'
vim --servername "$VIM_SERVERNAME" --remote-send "$send_string"
