#!/bin/bash
#
# Run a command but with vim's behaviour-changing environment variables unset.
# This is necessary to run different vims inside of vim,

unset MYVIMRC
unset VIM
unset VIMRUNTIME
unset VIM_TERMINAL
unset VIM_SERVERNAME
unset NVIM_LISTEN_ADDRESS

"$@"
