#!/bin/bash

if [ ! -t 1 ] ; then
    exec bash "$@"
fi

# Uncomment if set as login shell.
export DISPLAY=:0
source ~/.bashrc

tempfile="$(tempfile 2>/dev/null)"
export VIMSHELL_ID="$tempfile"
pwd > $VIMSHELL_ID
exec vim --servername "$VIMSHELL_ID" -c "call VimTerminalHostStart()"
