#!/bin/bash

if [ -z ${NORMAL_SHELL+x} ] ; then
    # Set NORMAL_SHELL locally to bash as a fallback.
    # NORMAL_SHELL should always be explicitly set, but just in case.
    NORMAL_SHELL=bash
fi

ls -l /proc/$$/fd > ~/test/tmp

if [ ! -t 1 ] ; then
    exec "$NORMAL_SHELL" "$@"
fi

# Don't open vimshell inside vim.
# NOTE: This assumes that $VIM is defined only when inside vim.
#       If that changes, this logic must be updated.
if [ -z "$VIM" ]
then
    exec "$NORMAL_SHELL" "$@"
fi

tempfile="$(tempfile 2>/dev/null)"
export VIMSHELL_ID="$tempfile"
pwd > $VIMSHELL_ID
exec vim --servername "$VIMSHELL_ID" -c "call VimTerminalHostStart()"
