#!/bin/bash

ls -l /proc/$$/fd > ~/test/tmp

if [ ! -t 1 ] ; then
    exec bash "$@"
fi

# Don't open vimshell inside vim. It is assumed the parent vim is a vimshell.
# TODO: More robust, better heuristic or even exact. e.g. currently vimshell detected in the terminal which spawned a new terminal emulator.
inside_vim=0
for pid in $(ppids) ; do
    if [ -r /proc/$pid/exe ] ; then
        exe="$(readlink -f /proc/$pid/exe)"
        if [ "$exe" = "$(which vim)" ] ; then
            inside_vim=1
        fi
    fi
done
if [[ $inside_vim -eq 1 ]] ; then
    exec bash "$@"
fi

# Uncomment if set as login shell.
export DISPLAY=:0
source ~/.bashrc

tempfile="$(tempfile 2>/dev/null)"
export VIMSHELL_ID="$tempfile"
pwd > $VIMSHELL_ID
exec vim --servername "$VIMSHELL_ID" -c "call VimTerminalHostStart()"
