#!/bin/bash
# warm: make colors warm

# todo: detect if xsct or sct

if [ $# -eq 1 ]
then
    n="$1"
else
    n=1
fi

case $n in
    0)
        xsct_number=0
        ;;
    1)
        xsct_number=3350
        ;;
    2)
        xsct_number=2750
        ;;
    3)
        xsct_number=2350
        ;;
    4)
        xsct_number=2000
        ;;
    *)
        xsct_number=2750
        ;;
esac


xsct $xsct_number

