#!/bin/bash
# wln: "web ln", create a URL link as an XDG desktop entry.
# 
# todo:
#  Why does caja only work with .desktop extension? Maybe want to use .link, or no extension.

if [ $# -ne 2 ]
then
    >&2 echo "Usage: wln <web URL> <link name>"
    exit 1
fi
url="$1"
link_name="$2"

# prefix http
# todo: Make sure works for all urls
if ! [[ $url =~ ^([A-Za-z])+:.*$ ]]
then
    url="https://$url"
fi

stub="[Desktop Entry]
Type=Link
Name=$link_name
URL=$url
"
if [ -e "$link_name.desktop" ]
then
    >&2 echo "Cannot create \"$link_name.desktop\": already in use."
    exit 1
fi
echo "$stub" > "$link_name.desktop"


# Variant which creates an HTML stub instead.
# #!/bin/bash
# # wln: "web ln", create a URL link as an html stub.
# 
# if [ $# -ne 2 ]
# then
#     >&2 echo "Usage: wln <web URL> <link name>"
#     exit 1
# fi
# url="$1"
# link_name="$2"
# 
# #todo: Does the URL ever need escaping?
# stub="<meta http-equiv=\"refresh\" content=\"0;url=$url\">"
# if [ -e "$link_name" ]
# then
#     >&2 echo "Cannot create \"$line_name\": already in use."
#     exit 1
# fi
# echo "$stub" > "$link_name"
