#!/bin/bash

if [ $# -ne 1 ] ; then
    echo "Usage: wp [image filename]"
else
    if [ "$(realpath $1)" == "/home/lucas/.wallpaper" ] ; then
        echo "Resetting wallpaper"
    else
        ls -l "$1"
        cp "$1" ~/.wallpaper
    fi
    feh --bg-fill "$1" "/home/lucas/drive/images/black.jpg"
fi

