#!/bin/bash
# xdg-browser: Run the default browser.

browser="$(xdg-settings get default-web-browser 2>/dev/null)"
if [ $? -ne 0 ]
then
    # xdg web browser setting failed.
    # Maybe no .desktop file.
    # Fallback to hardcoded browser.
    exec firefox "$@"
fi

exec gtk-launch "$browser" "$@"
