#!/bin/bash
# xwibind: Unfree (un-xwifree) target X window. This unapplies override_redirect to bring it back to the window manager.

if [ $# -eq 0 ]
then
    id="$(xwi)"
else
    id="$1"
fi

xdotool set_window --overrideredirect 0 "$id"
xdotool windowunmap $winid "$id"
xdotool windowmap $winid "$id"
