#!/bin/bash
# xwifree: Free target X window. This applies override_redirect to hide it from the window manager.

id="$(xwi)"
xdotool set_window --overrideredirect 1 "$id"
xdotool windowunmap $winid "$id"
xdotool windowmap $winid "$id"
