#!/bin/bash
# xwifree: Free target X window. This applies override_redirect to hide it from the window manager.

if [ $# -eq 0 ]
then
    id="$(xwi)"
else
    id="$1"
fi

xdotool set_window --overrideredirect 1 "$id"
xdotool windowunmap $winid "$id"
xdotool windowmap $winid "$id"
