#!/bin/sh

opacity=60
desktop_number=6

zathura --mode fullscreen "$@" &
pid="$!"
wid="$(xdotool search --sync --onlyvisible --pid "$pid")"
xwiopacity "$opacity" "$wid"

previous_desktop="$(wmctrl -d | grep ' \* ' | getcol 1)"

# Put it at a virtual desktop.
current_num_desktops="$(wmctrl -d | wc -l)"
if [ $current_num_desktops -lt $desktop_number ]
then
    wmctrl -n $desktop_number
fi
wmctrl -i -r "$wid" -t $((desktop_number - 1))
wmctrl -i -a "$wid"

# wait
# 
# wmctrl -s "$previous_desktop"
