#!/bin/bash
#
# Job control

free_args=()
while [[ $# -gt 0 ]]; do
    case $1 in
    *)
        free_args+=("$1")
        shift
        ;;
    esac
done

is_number()
{
    case "$1" in
        ''|*[!0-9]*) return 1 ;;
        *) return 0 ;;
    esac
}

if [[ ${#free_args[@]} -eq 1 ]] ; then
    job_number="${free_args[0]}" 
    if is_number "$job_number" ; then
        echo number
    else
        >&2 echo "Job number invalid: \"$job_number\""
        exit 1
    fi
fi

read
